apiVersion: v1
kind: Pod
metadata:
  name: fibonacci-pod
  labels:
    component: web
    name: fibonacci-pod
spec:
  containers:
  - name: fibonacci
    image: stephengrider/multi-worker
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 9999
